baseURL = "https://www.vertaefelungen.de/wissen/"
title = "Wissensdatenbank | Vert√§felung & Lambris"
theme = "papermod"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
ignoreFiles = [".*faq/restaurierung/index\\.md$"]

[outputs]
home = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]

  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
    [languages.de.params]
      locale = "de_DE"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      locale = "en_GB"

[languages.de.permalinks]
  produkte = "/:sections/:slug/"
  faq = "/faq/:sections/:slug/"

[languages.en.permalinks]
  products = "/:sections/:slug/"
  faq = "/faq/:sections/:slug/"
