baseURL = "https://www.vertaefelungen.de/wissen/"
title = "Wissensdatenbank | Vertäfelung & Lambris"
theme = "papermod"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

[outputs]
home = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]

  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
    [languages.de.params]
      locale = "de_DE"
    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "menu_shop"
        name = "Shop"
        url = "/wissen/de/shop/"
        weight = 10
      [[languages.de.menu.main]]
        identifier = "menu_faq"
        name = "FAQ"
        url = "/wissen/de/faq/"
        weight = 20
      [[languages.de.menu.main]]
        identifier = "menu_products"
        name = "Produkte"
        url = "/wissen/de/produkte/"
        weight = 30
      [[languages.de.menu.main]]
        identifier = "menu_lookbook"
        name = "Lookbook"
        url = "/wissen/de/lookbook/"
        weight = 40
      [[languages.de.menu.main]]
        identifier = "menu_about"
        name = "Über uns"
        url = "/wissen/de/faq/ueber-uns/"
        weight = 50

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      locale = "en_GB"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "menu_shop"
        name = "Shop"
        url = "/wissen/en/shop/"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "menu_faq"
        name = "FAQ"
        url = "/wissen/en/faq/"
        weight = 20
      [[languages.en.menu.main]]
        identifier = "menu_products"
        name = "Products"
        url = "/wissen/en/products/"
        weight = 30
      [[languages.en.menu.main]]
        identifier = "menu_lookbook"
        name = "Lookbook"
        url = "/wissen/en/lookbook/"
        weight = 40
      [[languages.en.menu.main]]
        identifier = "menu_about"
        name = "About us"
        url = "/wissen/en/faq/about-us/"
        weight = 50

[languages.de.permalinks]
  produkte = "/produkte/:sections/:slug/"
  faq = "/faq/:sections/:slug/"

[languages.en.permalinks]
  products = "/products/:sections/:slug/"
  faq = "/faq/:sections/:slug/"
