baseURL = "https://www.vertaefelungen.de/wissen/"
title = "Wissensdatenbank | Vert√§felung & Lambris"
theme = "papermod"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

[outputs]
home = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]

  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
    [languages.de.params]
      locale = "de_DE"
    [languages.de.menu]
      [[languages.de.menu.main]]
        name = "Shop"
        url = "de/shop/"
        weight = 10
      [[languages.de.menu.main]]
        name = "FAQ"
        url = "de/faq/"
        weight = 20
      [[languages.de.menu.main]]
        name = "Produkte"
        url = "de/produkte/"
        weight = 30
      [[languages.de.menu.main]]
        name = "Lookbook"
        url = "de/lookbook/"
        weight = 40

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      locale = "en_GB"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Shop"
        url = "en/shop/"
        weight = 10
      [[languages.en.menu.main]]
        name = "FAQ"
        url = "en/faq/"
        weight = 20
      [[languages.en.menu.main]]
        name = "Products"
        url = "en/products/"
        weight = 30
      [[languages.en.menu.main]]
        name = "Lookbook"
        url = "en/lookbook/"
        weight = 40

[languages.de.permalinks]
  produkte = "/de/produkte/:sections/:slug/"
  faq = "/de/faq/:sections/:slug/"

[languages.en.permalinks]
  products = "/en/products/:sections/:slug/"
  faq = "/en/faq/:sections/:slug/"
