baseURL = "https://www.vertaefelungen.de/wissen/"
title = "Wissensdatenbank | Vert√§felung & Lambris"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = false

[pagination]
  pagerSize = 10

[languages]

  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
    [languages.de.params]
      locale = "de_DE"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      locale = "en_GB"

[languages.de.permalinks]
  produkte = "/produkte/:sections/:slug/"
  faq = "/faq/:sections/:slug/"

[languages.en.permalinks]
  products = "/products/:sections/:slug/"
  faq = "/faq/:sections/:slug/"

[markup.goldmark.renderer]
  unsafe = true
