baseURL = "https://www.vertaefelungen.de/wissen/"
title = "Wissensdatenbank | Vert√§felung & Lambris"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
paginate = 10
canonifyURLs = true
relativeURLs = false

[languages]

  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
    [languages.de.params]
      locale = "de_DE"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      locale = "en_GB"

[permalinks]
  produkte = "/de/produkte/:slug/"
  faq_de   = "/de/faq/:sections/:slug/"
  products = "/en/products/:slug/"
  faq_en   = "/en/faq/:sections/:slug/"

[markup.goldmark.renderer]
  unsafe = true
